export const reglas =
[
    
{antecedents:["Enchiladas Verdes"],consequents:["Empanadas Huastecas"]},
{antecedents:["Pozole verde Huasteco"],consequents:["Empanadas Huastecas"]},
{antecedents:["Mole Rojo de Cerdo"],consequents:["Enchiladas Rojas"]},
{antecedents:["MOLE ROJO DE POLLO"],consequents:["Quesadillas de Pastor"]},
{antecedents:["Quesadillas Doradas"],consequents:["Mole verde de Pollo"]},
{antecedents:["Enchiladas Verdes","Enchiladas Rojas"],consequents:["Empanadas Huastecas"]},
{antecedents:["MOLE ROJO DE POLLO","Enchiladas Rojas"],consequents:["Empanadas Huastecas"]},
{antecedents:["MOLE ROJO DE POLLO","Empanadas Huastecas"],consequents:["Enchiladas Rojas"]},
{antecedents:["Mole Rojo de Cerdo","Empanadas Huastecas"],consequents:["Enchiladas Rojas"]},
{antecedents:["Mole rojo de Guajolote","Enchiladas Rojas"],consequents:["Empanadas Huastecas"]},
{antecedents:["Mole rojo de Guajolote","Empanadas Huastecas"],consequents:["Enchiladas Rojas"]},
{antecedents:["Enchiladas Rojas","Empanadas Huastecas"],consequents:["Mole rojo de Guajolote"]},
{antecedents:["Enchiladas Rojas","Pozole Huasteco"],consequents:["Empanadas Huastecas"]},
{antecedents:["Pozole verde Huasteco","Enchiladas Rojas"],consequents:["Empanadas Huastecas"]},
{antecedents:["Enchiladas Rojas","Quesadillas Doradas"],consequents:["Empanadas Huastecas"]},
{antecedents:["Enchiladas Rojas","Quesadillas de Bisteck"],consequents:["Empanadas Huastecas"]},
{antecedents:["Quesadillas de Huitlacoche","Empanadas Huastecas"],consequents:["Enchiladas Rojas"]},
{antecedents:["Enchiladas Verdes","Pozole Huasteco"],consequents:["Empanadas Huastecas"]},
{antecedents:["Mole verde de Cerdo","Empanadas Huastecas"],consequents:["Filete de Mojarra"]},
{antecedents:["Mole verde de Cerdo","Filete de Mojarra"],consequents:["Empanadas Huastecas"]},
{antecedents:["Pozole Huasteco","Filete de Mojarra"],consequents:["Empanadas Huastecas"]},
{antecedents:["Pozole verde Huasteco","Filete de Mojarra"],consequents:["Empanadas Huastecas"]},
{antecedents:["Quesadillas de Pastor","Filete de Mojarra"],consequents:["Empanadas Huastecas"]},
{antecedents:["MOLE ROJO DE POLLO","Pozole verde Huasteco"],consequents:["Empanadas Huastecas"]},
{antecedents:["Mole rojo de Guajolote","Empanadas Huastecas"],consequents:["Pozole verde Huasteco"]},
{antecedents:["Mole rojo de Guajolote","Pozole verde Huasteco"],consequents:["Empanadas Huastecas"]},
{antecedents:["Pozole verde Huasteco","Empanadas Huastecas"],consequents:["Mole rojo de Guajolote"]},
{antecedents:["Mole rojo de Guajolote","Quesadillas Doradas"],consequents:["Empanadas Huastecas"]},
{antecedents:["Mole verde de Pollo","Pozole verde Huasteco"],consequents:["Empanadas Huastecas"]},
{antecedents:["Mole verde de Pollo","Empanadas Huastecas"],consequents:["Pozole verde Huasteco"]},
{antecedents:["Pozole Huasteco","PASTEL DE CHOCOLATE"],consequents:["Empanadas Huastecas"]},
{antecedents:["Pozole verde Huasteco","Pozole Huasteco"],consequents:["Empanadas Huastecas"]},
{antecedents:["Pozole Huasteco","Quesadillas Doradas"],consequents:["Empanadas Huastecas"]},
{antecedents:["Pozole verde Huasteco","Quesadillas Doradas"],consequents:["Empanadas Huastecas"]},
{antecedents:["Quesadillas de Pastor","Empanadas Huastecas"],consequents:["Pozole verde Huasteco"]},
{antecedents:["MOLE ROJO DE POLLO","Mole rojo de Guajolote"],consequents:["Enchiladas Rojas"]},
{antecedents:["Mole Rojo de Cerdo","Mole rojo de Guajolote"],consequents:["Enchiladas Rojas"]},
{antecedents:["Mole Rojo de Cerdo","PASTEL DE CHOCOLATE"],consequents:["Enchiladas Rojas"]},
{antecedents:["Mole rojo de Guajolote","PASTEL DE CHOCOLATE"],consequents:["Enchiladas Rojas"]},
{antecedents:["Pozole verde Huasteco","Enchiladas Rojas"],consequents:["Mole rojo de Guajolote"]},
{antecedents:["Mole rojo de Guajolote","Quesadillas de Huitlacoche"],consequents:["Enchiladas Rojas"]},
{antecedents:["Quesadillas de Huitlacoche","Enchiladas Rojas"],consequents:["Mole rojo de Guajolote"]},
{antecedents:["Mole rojo de Guajolote","Sopes de Bistec"],consequents:["Enchiladas Rojas"]},
{antecedents:["Enchiladas Rojas","Sopes de Bistec"],consequents:["Mole rojo de Guajolote"]},
{antecedents:["Pozole verde Huasteco","Enchiladas Rojas"],consequents:["PASTEL DE CHOCOLATE"]},
{antecedents:["Filete de Tilapia","Quesadillas Doradas"],consequents:["Sopes de Bistec"]},
{antecedents:["Filete de Tilapia","Quesadillas de Huitlacoche"],consequents:["Quesadillas de Pastor"]},
{antecedents:["MOLE ROJO DE POLLO","Pozole verde Huasteco"],consequents:["Mole rojo de Guajolote"]},
{antecedents:["Mole verde de Cerdo","MOLE ROJO DE POLLO"],consequents:["Quesadillas de Pastor"]},
{antecedents:["Mole verde de Pollo","MOLE ROJO DE POLLO"],consequents:["Quesadillas de Pastor"]},
{antecedents:["MOLE ROJO DE POLLO","Quesadillas de Pastor"],consequents:["PASTEL DE CHOCOLATE"]},
{antecedents:["MOLE ROJO DE POLLO","PASTEL DE CHOCOLATE"],consequents:["Quesadillas de Pastor"]},
{antecedents:["MOLE ROJO DE POLLO","Pozole Huasteco"],consequents:["Quesadillas de Pastor"]},
{antecedents:["MOLE ROJO DE POLLO","Quesadillas Doradas"],consequents:["Quesadillas de Pastor"]},
{antecedents:["Mole verde de Cerdo","Pozole verde Huasteco"],consequents:["Mole rojo de Guajolote"]},
{antecedents:["Mole verde de Cerdo","Mole rojo de Guajolote"],consequents:["Quesadillas de Pastor"]},
{antecedents:["Mole verde de Pollo","Mole rojo de Guajolote"],consequents:["Pozole verde Huasteco"]},
{antecedents:["Mole verde de Pollo","Pozole verde Huasteco"],consequents:["Mole rojo de Guajolote"]},
{antecedents:["Mole rojo de Guajolote","Quesadillas Doradas"],consequents:["Mole verde de Pollo"]},
{antecedents:["Mole rojo de Guajolote","Quesadillas Doradas"],consequents:["Quesadillas de Pastor"]},
{antecedents:["Mole verde de Cerdo","Mole verde de Pollo"],consequents:["Quesadillas de Pastor"]},
{antecedents:["Mole verde de Cerdo","PASTEL DE CHOCOLATE"],consequents:["Quesadillas de Pastor"]},
{antecedents:["Mole verde de Cerdo","Pozole Huasteco"],consequents:["Quesadillas de Pastor"]},
{antecedents:["Mole verde de Cerdo","Quesadillas de Huitlacoche"],consequents:["Quesadillas de Pastor"]},
{antecedents:["Quesadillas de Pastor","Quesadillas de Huitlacoche"],consequents:["Mole verde de Cerdo"]},
{antecedents:["Mole verde de Pollo","Pozole verde Huasteco"],consequents:["PASTEL DE CHOCOLATE"]},
{antecedents:["Pozole verde Huasteco","PASTEL DE CHOCOLATE"],consequents:["Mole verde de Pollo"]},
{antecedents:["PASTEL DE CHOCOLATE","Quesadillas Doradas"],consequents:["Mole verde de Pollo"]},
{antecedents:["Mole verde de Pollo","Quesadillas de Pastor"],consequents:["PASTEL DE CHOCOLATE"]},
{antecedents:["Mole verde de Pollo","PASTEL DE CHOCOLATE"],consequents:["Quesadillas de Pastor"]},
{antecedents:["Quesadillas de Pastor","PASTEL DE CHOCOLATE"],consequents:["Mole verde de Pollo"]},
{antecedents:["Sopes de Bistec","PASTEL DE CHOCOLATE"],consequents:["Mole verde de Pollo"]},
{antecedents:["Mole verde de Pollo","Pozole verde Huasteco"],consequents:["Quesadillas de Pastor"]},
{antecedents:["Quesadillas de Pastor","Pozole verde Huasteco"],consequents:["Mole verde de Pollo"]},
{antecedents:["Quesadillas de Pastor","Quesadillas Doradas"],consequents:["Mole verde de Pollo"]},
{antecedents:["Sopes de Bistec","Quesadillas Doradas"],consequents:["Mole verde de Pollo"]},
{antecedents:["Mole verde de Pollo","Quesadillas de Huitlacoche"],consequents:["Quesadillas de Pastor"]},
{antecedents:["Mole verde de Pollo","Sopes de Bistec"],consequents:["Quesadillas de Pastor"]},
{antecedents:["Quesadillas de Pastor","Sopes de Bistec"],consequents:["Mole verde de Pollo"]},
{antecedents:["Pozole Huasteco","PASTEL DE CHOCOLATE"],consequents:["Quesadillas de Pastor"]}

]
 
